### ISSUE TITLE
Name of the boot partition

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#30]
Could the "boot" partition be named "WIFIBRDCAST, like in the legacy 1.6rc6 ?

**Comment by RespawnDespair** [comment]
Are you referring to the Label when you mount the SD card under windows?

**Comment by Yes21** [comment]
Yes, and under Linux to ...

It could be disturbing to some users not to find the WIFIBRDCAST SD card, which is mentioned in the wiki.

**Comment by Yes21** [comment]
Please, should you add this for 1.6.
I'm sure that many users will not understand that "boot" is the new name for "WIFIBRDCAST" partition ...

**Comment by RespawnDespair** [comment]
I will try, below link for my personal reference.

https://ubuntuforums.org/showthread.php?t=1113236

**Comment by Yes21** [comment]
I've found the command to do it :

`fatlabel /dev/mmcblk0p1 WIFIBRDCAST`

That's to be done from the Pi shell. So the command should be integrated into a "run-chroot.sh" script.

**Comment by RespawnDespair** [comment]
Feel up to making a pull request? Or should i add it sometime this week?

**Comment by Yes21** [comment]
Please could you add this by yourself, because I don't know in which part of which script to add it !
Thanks.

**Comment by Yes21** [comment]
I will make a PR

**Comment by pilotnbr1** [comment]
This pr should be reverted. Did not work. I think the dir location needs to be adjusted then the command should work

**Comment by Yes21** [comment]
Yes you're right. /dev/mmcblk0p1 doesn't exist when we are in the script.
So I need to find the good loop path for this partition ...

**Comment by pilotnbr1** [comment]
This might be possible to do on one of the non chroot files (run file). Thanks for putting in the time and looking at this!

**Comment by RespawnDespair** [comment]
I have added code for this on 99-run.sh in the 04 stage.
It's running now as a final test, but all appears good, i'll commit in a few minutes i hope.
After that this issue will be closed

**Comment by Yes21** [comment]
Thanks for your help guys !
I will replay all the script this evening with all latest PR.

**Comment by Yes21** [comment]
> I have added code for this on 99-run.sh in the 04 stage.

Are you sure ? I can't see anything new in 99-run.sh ...

**Comment by RespawnDespair** [comment]
It's not comitted yet, on my work pc, need to test it, but pretty sure it works

**Comment by Yes21** [comment]
Ok, thanks

**Comment by Yes21** [comment]
> I have added code for this on 99-run.sh in the 04 stage.

Could you please share your code, so I could also test it ?

**Comment by RespawnDespair** [comment]
I double double checked it, so i assume it works for everyone.

**Comment by Yes21** [comment]
I can confirm it works.
