### ISSUE TITLE
Display during boot sequence

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#31]
Would it be possible to see the EZ-WBC 1.6 splashscreen instead of raspbian boot sequence displayed lines ?

**Comment by RespawnDespair** [comment]
At some point during the boot it should show the EZWBC logo. This is the earliest point possible. In future i will optimize the time this logo is shown. It will timeout after 10 seconds now, if the boot is not yet complete you will see the text again. This is the same behavior as the normal EZWBC image

**Comment by Yes21** [comment]
I think that's important to see the splashscreen as long as possible for the final 1.6, because we will soon have a nice logo. That's important that this major version should show clearly the new logo, symbol of the revival of the project.

**Comment by RespawnDespair** [comment]
Agreed, put it in the 1.6 project pipeline. Will embed it a.s.a.p.

**Comment by Yes21** [comment]
Thanks ! But now you need to sleep ...

**Comment by Yes21** [comment]
**@RespawnDespair** 
I will sent send you soon the new splashscreen with the new logo. It will be nice for the final 1.6 !!

**Comment by Yes21** [comment]
**@RespawnDespair** : 
I don't where to find the original splashscreen file !
Do you know where it is ?

**Comment by RespawnDespair** [comment]
Yes, please do, i will implement it with image loading, it should look very nice while booting!
(In future in will make boot splash more interactive, but that will be one version later i think)

**Comment by RespawnDespair** [comment]
> **@RespawnDespair** :
> I don't where to find the original splashscreen file !
> Do you know where it is ?

It's implemented in the status app now, there is no image or anything, just text being sent to wbc_status.

**Comment by Yes21** [comment]
Oh sorry, I believed it was an image ...

**Comment by RespawnDespair** [comment]
@Yes21 Not yet, soon it will be 😄

**Comment by Yes21** [comment]
@**RespawnDespair** OK I prepare the image. Do you think that .png 1280x720 is suitable ?

**Comment by Yes21** [comment]
**@RespawnDespair** : Here is the new splashscreen image.

![ez-wbc_splashscreen-1 6](https://user-images.githubusercontent.com/33381245/47314397-cd46fd00-d641-11e8-90c4-ce2758ebb819.png)

**Comment by Yes21** [comment]
I've made little changes to the splashscreen :

![ez-wbc_splashscreen-1 6](https://user-images.githubusercontent.com/33381245/47375859-887a9f00-d6f1-11e8-8c60-f8be313cd088.png)

**Comment by Yes21** [comment]
You can find here how @seeul8er did for DroneBridge : [https://github.com/seeul8er/DroneBridge/tree/nightly/splash](https://github.com/seeul8er/DroneBridge/tree/nightly/splash)

**Comment by rodizio1** [comment]
While displaying a jpg or png image is certainly possible, there is the problem with the fixed resolution. In 1.6RC6, the splashscreen is a truetype font which is always drawn with the same size, regardless of resolution.

With an image you'll have the problem that a logo image made for a 1920x1080 screen won't fit on a 1280x720 or 640x480 screen and a 640x480 logo won't look good on a 1920x1080 screen.

I'd suggest looking into the openvg documentation and see if it's possible to scale jpgs or pngs down on the fly (and then use a logo image with a high resolution).

Another option would be to make jpgs/pngs with different resolutions and display the logo according to the detected resolution.

Or convert the Logo to a truetype font and display that (similar to the symbols in the OSD).

**Comment by RespawnDespair** [comment]
@rodizio1 Good to see you're back!
In the 'windowsave' branch there is the option to scale (or better stretch) the image.
I have implemented this in the `wifibroadcast-splash` repository.

It looks great as long as the aspect ratio of the screen does not vary to wildly.

**Comment by RespawnDespair** [comment]
As this is now implemented i'm closing the issue.
I'd like to expand on this idea, but for now we have other issues.

**Comment by Yes21** [comment]
Latest splashscreen with new version number.

![ez-wbc_splashscreen-2 0 beta1](https://user-images.githubusercontent.com/33381245/48025450-bb864f00-e143-11e8-98ee-18ee6d8ac7e8.png)
