### ISSUE TITLE
Reintroduce GPIO config selection.

### ISSUE THREAD

**Issue by RespawnDespair** [RespawnDespair/wifibroadcast-image-builder#32]
If it's easy to fix it now using only 2 pins (23, 24), I think it should do.

**Comment by Yes21** [comment]
What are we doing with that ?
The boss doesn't want we change anything !
https://github.com/rodizio1/EZ-WifiBroadcast/issues/151#issuecomment-443516925

Again Ok to implement this with 2 pins (23, 24) ?

**Comment by RespawnDespair** [comment]
I'm not completely sure how we want to do this. I sort of agree with the comments Rodi made, but i'm not sure how large the userbase for this functionality is.
Since it appears we're separating from the main EZ-WFB anyway, we might reconsider this functionality altogether. Don't spend any time on it for now...

**Comment by pilotnbr1** [comment]
Personally I see no reason to make modifications to the code to make fewer gpio work. Or no gpio support at all. 

For now I lean towards no gpio support as I think using an app is the future, like open hd.

**Comment by RespawnDespair** [comment]
Agreed, that was what i was aiming at, having several configs predefined in the app and switching on the fly seems more usable. 
In the near future, when the base of the image is proven correct we'll migrate the Open-HD modifications. At least, that's my plan, we'll need to discuss what to take and perhaps what not...

**Comment by Yes21** [comment]
I've never used GPIO to change configs, and will never use it.
So I'm Ok to abandon this feature, and to close this issue.

**Comment by pilotnbr1** [comment]
I spent some time looking into the gpio code. There is not much to it. Really just a short bash script connected to a short bit of python which sets the selected wifibroadcast-xx.txt to the active settings. At least that’s what I see...

All this has to occur before cards initialize. I just don’t see where or how it is being triggered. More poking around and educating myself.

**Comment by Yes21** [comment]
So, could we close this issue now ?

**Comment by pilotnbr1** [comment]
I think I can get the gpio pins working again. Going to try in the next hour. But for record keeping sake here is what I see in 1.6

etc/Systemd/system has a oneshot service named wbcconfig.service 

wbcconfig.service calls /root/wifibroadcast_misc/wbcconfig.sh

wbcconfig in turn references /root/wifibroadcast_misc/gpio-config.py

in gpio-config.py it "import RPi.GPIO" which is managed by raspbian and monitors gpio pins on boot

**Comment by pilotnbr1** [comment]
for gpio support do you guys want 16 wifibroadcast-xx.txt files? For now only did a PR for a wifibroadcast-2.txt

**Comment by pilotnbr1** [comment]
I believe all 7 gpio related PRs in both repos are complete

Should all work!

**Comment by pilotnbr1** [comment]
Ok to close by me....
