### ISSUE TITLE
Raspberry Pi 3B+ (Kernel8 support)

### ISSUE THREAD

**Issue by RespawnDespair** [RespawnDespair/wifibroadcast-image-builder#34]
http://www.tal.org/tutorials/raspberry-pi3-build-64-bit-kernel

**Comment by RespawnDespair** [comment]
If all is well the new image should be RPI3B+ compatible.

**Comment by rodizio1** [comment]
Just to avoid possible confusion: Kernel8 (or 64bit Kernel) is not needed for the new RPI 3B+. In fact, we don't need a 64bit kernel at all for our purposes.


Pi 3B+ support was introduced with Raspbian 2018-03-13 release which included:
 * Linux kernel 4.9.80+
  * Raspberry Pi firmware 3347884c7df574bbabeff6dca63caf686e629699

So any firmware/kernel after that should be fine.

**Comment by RespawnDespair** [comment]
I know (now), but thanks for posting.
I only generate the kernel.img for older pi's and the kernel7.img for the newer pi's including Pi3B+.
Originally i tried generating kernel8.img as well, but like you stated it's not needed.
