### ISSUE TITLE
rasbian lite zip file corrupt

### ISSUE THREAD

**Issue by dposea** [RespawnDespair/wifibroadcast-image-builder#36]
I ran the full build until it failed because the rasbian zip was missing an eof.

~/src/wifibroadcast-image-builder ~/src/wifibroadcast-image-builder
Archive:  2018-06-27-raspbian-stretch-lite.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of 2018-06-27-raspbian-stretch-lite.zip or
        2018-06-27-raspbian-stretch-lite.zip.zip, and cannot find 2018-06-27-raspbian-stretch-lite.zip.ZIP, period.

**Comment by Yes21** [comment]
I can't confirm this issue.
For me the process goes to the end without errors, and I get a **2018-06-27-raspbian-stretch-lite_2018-10-22.img** and a "2018-06-27-raspbian-stretch-lite_2018-10-22.zip".

Perhaps a download error ?

**Comment by RespawnDespair** [comment]
This might be related to not running under Ubuntu as well, since no other users reported this issue i'm going to assume this was the case. When you run into the same issue under Ubuntu feel free to reopen.
