### ISSUE TITLE
More errors on LinuMint

### ISSUE THREAD

**Issue by dposea** [RespawnDespair/wifibroadcast-image-builder#37]
+ sudo systemctl stop dhcpcd.service
Running in chroot, ignoring request.
+ sudo systemctl disable dhcpcd.service
qemu: Unsupported syscall: 384
Synchronizing state of dhcpcd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable dhcpcd
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US,",
	LC_ALL = "en_US.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US,",
	LC_ALL = "en_US.UTF-8",
	LC_MESSAGES = "en_US.UTF-8",
	LC_CTYPE = "en_US.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
+ sudo apt install python-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2+rpt2).
0 upgraded, 0 newly installed, 0 to remove and 39 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
E: Sub-process /usr/bin/apt-listchanges --apt || test $? -lt 10 returned an error code (1)
E: Failure running script /usr/bin/apt-listchanges --apt || test $? -lt 10

I don't expect you to spend any time fixing this. It's much more important for you to create images with the latest fixes and enhancements. I just wanted to inform you of possible problems. I think the apt problem is qemu related and I may try to debug it late tonight. If I figure it out I'll add to this issue.

**Comment by Yes21** [comment]
The script has been developed and tested with Ubuntu, but not with LinuxMint ...

**Comment by RespawnDespair** [comment]
As stated by @Yes21 and in the readme this script works ONLY on Ubuntu (18).
Closing this issue.
