### ISSUE TITLE
"Ethernet connected IP :"

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#39]
When ethernet connection is set up, the message "Ethernet connected IP :" doesn't shows the ip adress.

**Comment by RespawnDespair** [comment]
I checked in a fix, maybe you can manually edit the main.sh script found on the pi at /home/pi/wifibroadcast-scripts

line 121:
```
#ETHCLIENTIP=`ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1`
ETHCLIENTIP=`ip addr show eth0 | grep -Po 'inet \K[\d.]+'`
```

And then reboot and try connecting the ETH0 again.

The output of the ifconfig command seems to have changed.

**Comment by Yes21** [comment]
I've just tried this, but now I have no more message at all, even if the Pi is well ethernet connected.

**Comment by RespawnDespair** [comment]
Have you typed it manually or copied?
If you typed it, make sure you used a 'backtick'  '`' character instead of regular ''' character for the first and last quote.
Else you would get an exception on one of the TTY's.

**Comment by Yes21** [comment]
I couldn't copy/paste into the terminal, so I'd typed it manually.
I think I've typed " ` ", but did perhaps make others errors.
Will see it tomorrow. That's not so important.

**Comment by Yes21** [comment]
That's now working for me.
I'd made a mistake ... Sorry !

**Comment by RespawnDespair** [comment]
No problem, can the issue be closed?
