### ISSUE TITLE
File system "ro" after ssh connection

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#40]
When connected via ssh, the file system remains "read only" ( in 1.6rc6 it becomes writable when a ssh connection is open).

> To make the system rw manually you can just type rw.

**Comment by Yes21** [comment]
I can't confirm this issue. The file system is rw when ssh.

I think my problem was that with 1.6rc6, I could ssh with root@192.168.0.18.
With your image I can't anymore log with root@192.168.0.18, but only with pi@192.168.0.18.
So I've to sudo each time I want to do something ...

**Comment by RespawnDespair** [comment]
No thread necromancy here, but in the latest image-builder the filesystem should be readonly...Haven't checked to be honest.

**Comment by rodizio1** [comment]
In the original 1.6RC6 image, root is allowed to login via ssh and the password is set to "raspberry" also for root, (see /etc/ssh/sshd_config), maybe that is not the case in the image builder images?
