### ISSUE TITLE
No video/telemetry transmission with CSL300 (Ralink rt5572)

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#41]
I think my problem is on my airPi and my wifi board (CSL300 - rt5572)
So I've connected my hdmi screen on it.
The boot is ok, and the wifi board set in monitor mode.
But after that, I see a continuous flow of lines which never stops (see joint picture).
I never had this problem with the same setup and 1.6rc6 ...
That's certainly a specific problem with ralink rt5572, but I've any other compatible wifi board.

![img_20181023_174402](https://user-images.githubusercontent.com/33381245/47376866-1061a880-d6f4-11e8-8215-6672befa4f5c.jpg)

**Comment by htcohio** [comment]
@RespawnDespair please see my notes and video above.

Your image had RC and internal hotspot disabled.  

I tested as is and also enabled hotspot RC for the second test. 

Both resulted in poor video.
*I thought it was the result of an under voltage error but I checked the logs and there weren't any.

**Comment by RespawnDespair** [comment]
@htcohio can you share the wifibroadcast-1.txt you normally use?
I think the version i have included in the overlay/boot folder has some default settings that are not 'optimal'. Even when running kernel7.img on the pi3b+ i wouldn't expect a 2 second lag.
RC and hotspot are indeed disabled in the config i now have.

**Comment by htcohio** [comment]
Here is the wfb and apconfig.txt settings

https://www.dropbox.com/sh/euk4vgk8rj2dyrn/AAArdI0ZB1IvMoq2xZ3IycVHa?dl=0

**Comment by RespawnDespair** [comment]
Understood, so the defaults in my config are ok, except for the RC and hotspot.
I will keep FREQ in the 24xx range for dongles that don't support 23xx range by default.

I hope to hear from user1321 about the Pi3B+ image, i really want to support that, going to order one for myself next week in order to be able to test quicker.

**Comment by Yes21** [comment]
CSL300 is now working.
