### ISSUE TITLE
Problem with /lib/modules/4.14.54*/build and source

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#43]
These links are pointing to "_/home/jelle/git/wifibroadcast-image-builder/data/kernel/linux_" and "_/home/jelle/git/wifibroadcast-image-builder/data/kernel/linux7_" !

I don't know exactly what should be the correct links ? 

I've noticed it because I couldn't anymore compile the aircrack-ng/8812au driver.

```
make ARCH=armv7l CROSS_COMPILE= -C /lib/modules/4.14.54-v7+/build M=/home/pi/rtl8812au  modules
make[1]: *** /lib/modules/4.14.54-v7+/build: No such file or directory.  Stop.
Makefile:1933: recipe for target 'modules' failed
make: *** [modules] Error 2
```

Ps : I've noticed others bad symlinks in others places, but can't find them again ...

**Comment by RespawnDespair** [comment]
You are trying to compile on the generated image on the pi itself?
I compile everything under chroot on the host machine, so i never ran into this issue.
Offcourse the symlinks shouldn't point to my dev structure once the image is mounted, i will look into this.
For now, if you can give me the exact commands to run in order to make the drivers work i can include it in the builder.

**Comment by RespawnDespair** [comment]
One possible fix would be to copy the kernel source to the mounted chroot image and then compile the kernel there, but that would leave a lot of 'crap' in the image that normal users would not need...

**Comment by Yes21** [comment]
Yes, I'm using your last image (not the one for rpi3b+) and I'm try to install the driver being connected via ssh.
I will send you the code in the dedicated issue. But it doesn't work !
I had it working with your script in august ...

**Comment by Yes21** [comment]
I've built a new image with your latest modifications (2018-10-09-raspbian-stretch-lite).

The "/lib/modules/4.14.78*/build and source" are now symlinks pointing to "/home/yves/ez-wbc/wifibroadcast-image-builder/data/kernel/linux" and "/home/yves/ez-wbc/wifibroacast-image-builder/data/kernel/linux7".

I've replaced these bad links (in the image) by the linux and linux7 directories from data/kernel (from my hd).
That should be correct ...

But the aircrack-ng/8812au driver fails now because of kernel-headers :
```
make ARCH=armv7l CROSS_COMPILE= -C /lib/modules/4.14.78-v7+/build M=/home/pi/rtl8812au  modules
make[1]: Entering directory '/lib/modules/4.14.78-v7+/build'
Makefile:642: arch/armv7l/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/armv7l/Makefile'.  Stop.
make[1]: Leaving directory '/lib/modules/4.14.78-v7+/build'
Makefile:1933: recipe for target 'modules' failed
make: *** [modules] Error 2


It's a long way ... !

```

**Comment by Yes21** [comment]
> So even when the driver works it won't work without also modfying the source code of the wfb system.

I know it ! 
My intention was to inform you that something is wrong in /lib/modules/.
 
I was only trying to install the driver, and ran into these kernel modules and headers problems, that I didn't had in august ...

But be careful. The .diff file you have (EZ-Wifibroadcast-1.6RC6+8812au.diff ?) doesn't have the latest modifications done by Lelik for his latest image, which is the best working.

Many thanks to you.

**Comment by RespawnDespair** [comment]
Yeah that's the diff file i based my modifications on (just checked them in...)
Now if somebody could point me to that image...

**Comment by Yes21** [comment]
This diff file is coming from here ([http://forum.rcdesign.ru/f90/thread515083-9.html#post7446277](http://forum.rcdesign.ru/f90/thread515083-9.html#post7446277)) and was posted on 20.08.2018.
The link for the last image is here ([https://www.rcgroups.com/forums/showpost.php?p=40322154&postcount=6087](https://www.rcgroups.com/forums/showpost.php?p=40322154&postcount=6087)), posted on 08.10.2018.

**Comment by Yes21** [comment]
> The "/lib/modules/4.14.78*/build and source" are now symlinks pointing to "/home/yves/ez-wbc/wifibroadcast-image-builder/data/kernel/linux" and "/home/yves/ez-wbc/wifibroacast-image-builder/data/kernel/linux7".

Perhaps this could help to preserve the symlinks ?



- **Convert absolute symlinks into relative symlinks**
```
    wget https://raw.githubusercontent.com/riscv/riscv-poky/master/scripts/sysroot-relativelinks.py
    chmod +x sysroot-relativelinks.py
    ./sysroot-relativelinks.py sysroot
```

**Comment by dposea** [comment]
I'm trying the latest build now, but the build process completed sucessfully. I had some restarts due to wifi issues , but restarting also worked well. Even with the Russian changes I can't get RTL8814au working correctly as a transmitter. Still trying to isolate the issues, but I get a lot of dropped packets on the ground pi RX stats from ifconfig. Next I'll up the number of FECS.

**Comment by Yes21** [comment]
@dposea did you try the rtl8814 as reciever (ground) ? Does it work ?

**Comment by Yes21** [comment]
@RespawnDespair 

> These links are pointing to "/home/jelle/git/wifibroadcast-image-builder/data/kernel/linux" and "/home/jelle/git/wifibroadcast-image-builder/data/kernel/linux7" !

I don't remember if that is fixed now ?
If yes, I will close the issue.

**Comment by Yes21** [comment]
**@dposea** I will close this issue now.

If you have other problems with 8814, please feel free to share it [here](https://github.com/bortek/EZ-WifiBroadcast/issues/166) or [here](https://github.com/bortek/EZ-WifiBroadcast/issues/105).

I'll soon try to connect my AWUS1900 on my airPi, and see if I can reproduce your problems ...
