### ISSUE TITLE
Bake in v4l2loopback kernel modules to build scripts

### ISSUE THREAD

**Issue by kwatkins** [RespawnDespair/wifibroadcast-image-builder#45]
It's a bit of a struggle post to add this in, is it possible to include it into the build scripts? 
Used for alternate types of gstreamer and video inputs.

**Comment by careyer** [comment]
:+1: This also adds the basis for FLIR, Seek (Thermal camera) + insta360 support. Would be very convenient to have that complied in already.

**Comment by RespawnDespair** [comment]
I will add it to the (new) build script. I'm also integrating the dino.de modifications which include the FLIR + insta support

**Comment by careyer** [comment]
This is exzellent news. Thank you very much. :-)

Keep it going. #highfive

Von meinem iPhone gesendet

**Comment by kwatkins** [comment]
@RespawnDespair - really digging all the work your doing with this project, it's exactly what we need... quick question, where is the dino.de modifications/image that I keep seeing referenced?

**Comment by RespawnDespair** [comment]
@kwatkins right here:
https://www.dropbox.com/s/yzavlwsfrcbys57/EZ-Wifibroadcast-1.6RC6_FlirOneG2_v0.9_omxh264_MavLinkv2_GPIO.img?dl=0

**Comment by pilotnbr1** [comment]
So I have code done that gits v4l2loopback and places it in the right place. However I believe the make process is failing.

@RespawnDespair do you want me to make a pull or further refine this? Looking into it I believe it is failing due to a kernel header string mismatch... 

I know this subject was discussed and some very detailed steps giving by @kwatkins to make all this work in the EZ repository. Looks kind of involved... Additionally it looks like for their flir application additional sources might need to be cloned in, which I am happy to tackle or double check.

**Comment by Yes21** [comment]
@pilotnbr1 That's perhaps also related to [this](https://github.com/RespawnDespair/wifibroadcast-image-builder/issues/61) issue ?

**Comment by pilotnbr1** [comment]
@Yes21 yes very possible. When trying to make v4l2 on a live image the error refers to ( off the top of my head not exact) a "build" dir not found in the kernel dir... 

further down here too @careyer says he had this problem https://github.com/bortek/EZ-WifiBroadcast/issues/71

Careyer-

" The commands above load the kernel sources (or headers) for 4.9.35-v7+ wheras EZ-Wifibroastcast v1.6RC3 runs on 4.9.35-v7 (non+). Maybe that is why the kernel module compiles okay but does not get installed properly?

Can you please advice me how to install the correct kernel sources/headers for 4.9.35-v7 ((and how exactly to apply the patches you made). I took a look at https://github.com/bortek/EZ-WifiBroadcast/tree/master/kernel/readme.md but I do not completely understand how to do it. You know... me just being a linux noob! "

**Comment by Yes21** [comment]
> You know... me just being a linux noob! "

Me too !!
It's also perhaps related to this [other issue](https://github.com/RespawnDespair/wifibroadcast-image-builder/issues/67).
You will find here a dirty way for getting the right kernel headers ...

**Comment by pilotnbr1** [comment]
@Yes21 I tried sudo apt-get install raspberrypi-kernel-headers in the builder and I still get the same error.. Do you know if that command gets the latest headers or the ones specific to your kernel?

I was looking at the symlinks for the build file and comparing images in a file browser
1.6 build symlink points to /usr/src/kernel/v-7 (I didn’t write it down)
2.0 points to a local dir in my work folder of the builder

I don’t understand this.. and I see another issue was created by you regarding symlinks

I am going to look at this closer in a live image.

**Comment by RespawnDespair** [comment]
The symlinks are broken because we build the kernel outside of the image (crosscompile) i believe.
There was a script posted a while back that should fix all symlinks, but i never had a chance to try it (can't find it anymore).
Perhaps after the kernel stage we can run this script to restore the symlinks in a chroot.
Building should work fine then.

**Comment by Yes21** [comment]
> Do you know if that command gets the latest headers or the ones specific to your kernel ?
This should install the same version as the kernel !
It's working like this on a regular raspbian ...
I didn't find how to force apt-get to install a particular version.
And don't know why it is installing the wrong version in our built image.

**Comment by pilotnbr1** [comment]
@Yes21 @RespawnDespair 
I"ll look into this symlink issue today and try to find a fix. We shouldnt have to run this apt-get for kernel headers...

**Comment by Yes21** [comment]
Yes21 but these symlinks are pointing to kernel headers and they are created by kernel headers installation ...
When kernel headers are not installed, the symlinks should not exist.

**Comment by Yes21** [comment]
The best way to understand it is to burn on a sd the /work/01-Baseimage/2018-10-09-raspbian-stretch-lite.zip.
Verify that the symlinks doesn't exist.
Then `sudo apt-get install raspberrypi-kernel-headers`
Verify that good version of kernel-headers are installed, and that the correct symlink to it is created.

**Comment by Yes21** [comment]
I believe I have found. That is because these lines in `03-Packages/00-run-chroot.sh`

```
# Latest package source
sudo rm -rf /var/lib/apt/lists/*
sudo apt-get clean
sudo apt-get update 
```
One should `apt-get update` only if he wants then to `apt-get dist-upgrade`.
With `apt-get update` we are now pointing to the latest sources for all packages.

I think that shouldn't be done.
I will now build an image with those 3 lines commented.
Will tell you later the result.

**Comment by pilotnbr1** [comment]
Nice work @Yes21 ! I will have a pr for v4l2loopback support tonight. I will also add a few packages that these flir guys want.

One quick proposal for builds in general is I have been adding a line in the chroot files for "echo" to show progress. It helps when monitoring the build for example-
echo ">>>>>>>>>>>>> STARTING Stage 4 03-run-chroot.sh <<<<<<<<<<<<<<<<<<<<

Additionally I propose a developer stage folder be the very last stage. That way all the other stuff can be skipped and just go to the lines you are currently working on. It would really speed up these builds I do to test stuff

**Comment by RespawnDespair** [comment]
@pilotnbr1 during the build it already shows what stage you are on, i could add it also shows which file. That would prevent the need for the echo.

Also, you are free to add a developer stage, but there is always the problem that some modifications needs to be done in a specific stage of the proces. So having a developer stage as stage 5 would not cover the scenario where you need to modify the kernel...
Any thoughts on that?

**Comment by pilotnbr1** [comment]
@RespawnDespair that is true where you cant make all mods at the end. Maybe I will just leave it as is then. Yes each page would be helpful for progress. So amny lines get output to terminal I found myself spending alot of time scrolling trying to find where in that stage my mod was. But whatever you think- I have no strong feelings- I can always just echo while I am testing and delete it later before the commit.

**Comment by pilotnbr1** [comment]
@RespawnDespair do you think we need to mount --bind more files in the builder script (lib dir)? It seems like most files are correctly associated but then other stuff is not...

**Comment by pilotnbr1** [comment]
> The symlinks are broken because we build the kernel outside of the image (crosscompile) i believe.
> There was a script posted a while back that should fix all symlinks, but i never had a chance to try it (can't find it anymore).
> Perhaps after the kernel stage we can run this script to restore the symlinks in a chroot.
> Building should work fine then.

As @Yes21 has said in other posts the kernel headers do not seem to be there at all. We have a “vanilla” installation as /usr/src is empty.

Running sudo apt-get install raspberrypi-kernel-headers in the builder has only installed the latest headers, which are incorrect.

Trying to retrieve them through rpi-source and their repository errors out as well. (This might be made to work)

Is it possible to build the headers for our kernel on an internet connected pi and then just copy the src dir into the builder for future use?

**Comment by Yes21** [comment]
I propose to install kernel-headers in the script before applying apt-get update.
This should work ...
I will test it this afternoon, and make a PR if it works.

**Comment by RespawnDespair** [comment]
Sounds like a plan. Thank you guys for sticking with this issue!

**Comment by pilotnbr1** [comment]
It is very difficult to get the correct headers in the builder

DEBIAN_FRONTEND=noninteractive sudo apt-get purge -yq raspberrypi-kernel-headers
DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install raspberrypi-kernel-headers

I only get the most recent kernel headers... there is no usage I am aware of to do 

install raspberrypi-kernel-headers-KERNEL HEADER VERSION


I have tested rpi-source and no luck

sudo wget https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source -O /usr/bin/rpi-source && sudo chmod +x /usr/bin/rpi-source && /usr/bin/rpi-source -q --tag-update

sudo rpi-source

I think it might be breaking because of the host machine file system not replicating an rpi completely while cross compiling

**Comment by Yes21** [comment]
> `DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install raspberrypi-kernel-headers`

@pilotnbr1 I will try to insert this command in the script before `apt-det update`.
Please could you wait till the end of afternoon that I have tested it.
I also need the code remains unchanged before I had fix the OSD problem.
So please can you wait before submitting a new PR ?
Thanks for your help !

**Comment by RespawnDespair** [comment]
@pilotnbr1 Yes, the master branche should be kept stable.
**In theory i expect all PR's to be tested before they become PR's.**
I do read through the modifications before approving, but i don't test everything before approving the PR itself.
Right now we have 4 PR's which i don't know if they can be merged or not. So if everybody would update their PR's with a comment about the status i'd be very happy.

**Comment by pilotnbr1** [comment]
Understood! Yes my PRs were tested and stable to the best of my knowledge 😀

**Comment by RespawnDespair** [comment]
As stated in the last PR, this is now included in the master branch!

**Comment by careyer** [comment]
Hi everyone.

I am back from my cruise and seems like Jelles's repo is the new place to be. I thoroughly documented how to successfully build the v4l2loopback and flir stuff. If it is of any help I can share my step by step guide. It indeed was a kernel string mismatch problem - removing the "+" appendix at certain locations helped to solve the problem. 

Cheers! 

Von meinem iPhone gesendet

**Comment by RespawnDespair** [comment]
@careyer i'm pretty sure the master branche now includes the v4l2loopback modules.
If somebody could verify that would be great.
I hope you had some relaxation on your cruise as well!

Cheers!
