### ISSUE TITLE
8812au support

### ISSUE THREAD

**Issue by RespawnDespair** [RespawnDespair/wifibroadcast-image-builder#46]
Implement kali drivers and 'russian image' source mods.

**Comment by Yes21** [comment]
**@RespawnDespair** 
Thanks to @seeul8r (DroneBridge) I've discovered an other smart way (that works for me) to install the aircrack-ng/8812au driver. See here : [https://github.com/DroneBridge/RPiKernel](https://github.com/DroneBridge/RPiKernel)
I think you could easily use that way for your building script ... ?

**Comment by RespawnDespair** [comment]
I have included the kernel compilation from dronebridge (albeit modified) in the new builder (staged branche).
I have also included the various modifications from the 'Russian' image.
