### ISSUE TITLE
Make the building script use a determined number of CPU cores

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#47]
I found this on DroneBridge github :

> Compile the kernel using make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs -j 8 where 8 is your CPU core count.

I have 12 cores. Do you think it could be much faster if I could use "-j 12" ?

**Comment by RespawnDespair** [comment]
yes, it would be a lot faster

**Comment by RespawnDespair** [comment]
Would it help to make this a config setting? So you can specify in the config before starting the build?
I have no idea what it would do if i set it to 12 permanently and somebody runs it on a two core machine...

**Comment by Yes21** [comment]
Included in https://github.com/RespawnDespair/wifibroadcast-image-builder/issues/52
