### ISSUE TITLE
Feature request: Add support for recent wifi chipsets

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#5]
The list of wifi cards supported by ez-wbc is pretty old, and didn't evolve since 2015 !!
Many of the supported cards are old, or not manufactured anymore (especially dual bands cards).
There are now very promising dual band long range cards from Alfa Networks :

  -  AWUS036ACH (RTL8812au)
  - AWUS1900 (RTL8814au)

The architecture of ez-wbc is so old and difficult, that nobody could add support for now chipsets ...

The best drivers are perhaps here : [https://github.com/aircrack-ng/rtl8812au](https://github.com/aircrack-ng/rtl8812au)

I wonder if these drivers could be installed by your script ?

**Comment by RespawnDespair** [comment]
It looks simple enough with the scripts from the aircrack-ng github. This could be done to the existing EZ-WBC image as well if you want. all try to add it to the script. Do you have these adapters? For testing?

**Comment by Yes21** [comment]
Yes, I have these cards.

But I can't install anything on the image, because I can't connect my Pi to a router. So no ssh for me !
And perhaps the kernel from original image would be to old for these drivers ?
So that's why I want to try to install them with your building script.

But I don't know if it will be enough to have working drivers, for making the cards work with ez-wbc.

If you have a little time, perhaps you could just give me the few lines I have to add to the script.
It could help me (and others) to add something else later.

An other question : could I run the created image with qemu, and then connect to it to and install the drivers ?

**Comment by Yes21** [comment]
I've succeed in adding a few lines into your scripts to install the aircrack-ng/8812au drivers.
I didn't have any errors along building process, but can't try the image now.
Will tell you later how it works into a Pi with alfa awus036ac/h and awus1900.
I haven't many hope, because I think that ez-wbc code should be adapted too ...

**Comment by Yes21** [comment]
I have now tried my new image in my rx and tx Pis, and I can say that the adding of aircrack-ng/8812au drivers doesn't change anything to alfa awus036ac/h or awus1900 cards support.
At least I can confirm that the image created by your script is working very well, exactly like Rodizio's one, but with a newer kernel and patches.
It should be a good base for helping ez-wbc and DroneBridge to support new wifi cards, and Pi3b+ ...

Thank you very much for this script, which may help many of us in the near future.

**Comment by RespawnDespair** [comment]
It's good that you can confirm the image works, i had some issues myself due to bad wifi dongles. I've ordered new ones, but it might take some time. Do the awus036ac/h not work at all or is there some error? It would be nice to have a broader range of wifi cards supported.

**Comment by Yes21** [comment]
The awus036ac/h is working on the rx Pi but not on the tx, like with Rodizio's image. He did add a rtl8812au driver since the 1.6rc1 (Release note : "Support for RTL8812AU cards added (only RX, not tested, for experimenting"). Tha awus1900 isn't detected on rx or tx.
I can't say more now, because I can't connect my Pis to the router (too faraway from my office). This will perhaps change in a few days/weeks.

**Comment by roque-canales** [comment]
does anyone could share image with last kernel and 8812au aircrackng driver for I test?

I have RX/TXsetup waiting with two pi3 and and two AWUS036ACH correctly soldered and powered.

Please share it through wetransfet my email kuspower@live.fr

**Comment by Yes21** [comment]
I've build a new image with aircrack-ng/8812au 5.2.20 drivers instead of 5.3.4.
I'm not totally sure that the drivers are correctly installed, because I can't see any difference.
One can dowload this image [here]( https://drive.google.com/open?id=14kkL5wKGUA06eq9J9Ylt5AkKRveY6ruu).

**Comment by Yes21** [comment]
**@RespawnDespair**
You can find here the 2 scripts in which I added a few lines. Please could you have a look and tell me if that seems correct to you ?

[yes21_modified_scripts_wbc-ib.zip](https://github.com/RespawnDespair/wifibroadcast-image-builder/files/2342483/yes21_modified_scripts_wbc-ib.zip)

**Comment by RespawnDespair** [comment]
@Yes21, your modifications look good. I could integrate it into the main, OR you could make a pull request, that way it will be YOUR contribution instead of mine. Subtle difference, but i do want to encourage pull requests to the repositories, so if you would like to do it that way. Otherwise, let me know and i will integrate the modifications.

**Comment by Yes21** [comment]
**@RespawnDespair**, Ok I will make a pull request. But I will wait a little time before someone else test the image with aircrack-ng/8812au 5.2.20 drivers. I'm not really sure if these drivers brings something new to rtl8812au support ! The 5.2.20 branch didn't support anymore rtl8814au, but 5.3.4 does it again and seems very promising. But this branch is too new and not stable now.

**Comment by htcohio** [comment]
Respawn, seeul8er and yes21,

Is there any chance that Wi-Fi broadcast would be compatible with wireless cards that have an Ethernet interface as opposed to just USB? There seem to be many more options available from an Ethernet interface standpoint however, I am not technically inclined to understand the difference related to drivers and compatibility with monitor packet injection modes.

For an example, Ubiquiti has the picostations and Nanostations which utilize atheros chipsets and openwrt. 

I have a business that installs wireless networks and I wonder what kind of flexibility and progress could be made with a 12 Port switch on the ground with multiple poe adapters networked together.

Is it just not possible due to drivers?

https://wiki.openwrt.org/toh/ubiquiti/nanostationm2

**Comment by Yes21** [comment]
> At least I can confirm that the image created by your script is working very well, exactly like Rodizio's one, but with a newer kernel and patches.

I'm so sorry for this bad news, but I've just realised that my image was not really written on the sd card. So I was testing the regular 1.6rc6 from Rodizio  ;(  !!
I'm so confused ...

I can now understand some issues reported by other users.
I will create new issues.

Ps : I can now connect to my Pis with ssh. It will be easier for my further tests.

**Comment by RespawnDespair** [comment]
@htcohio I am not as knowledgeable as Rodizio and others when it comes to the intricacies of the USB WiFi dongles. I do believe there is some poking and prodding going on the get the dongles to allow the sending of a stream on the TX without an actual peer to peer connection (hence the broadcast in the name) . The RX needs to be put in 'monitor' mode where it also receives all packages, regardless of any peer to peer connection. To put these dongles into said modes, the driver needs to allow it, and as such i think it very likely they have to be connected directly to the Pi. I do not think there is any way to put the dongles into these modes remotely over a network connection...

**Comment by Yes21** [comment]
I close this issue now, because it will be treated later on bortek's github.
But I don't forget it, because here are the few lines of code I'd added to install aircrack-ng/8812au 5.2.20 or 5.3.4 driver (for 1.7 ?)

**Comment by Yes21** [comment]
@RespawnDespair 
Perhaps you could implement now (before 1.6 final) my adds for installing aircrack-ng/8812au 5.2.20 ?
It won't add support for 8812au, but it will be ready when other developers will try to adapt ez-wbc code for full 8812au support.

(I don't understand how pull request is working, and your build/install scripts have changed since my adds ...)

**Comment by Yes21** [comment]
Here is the code to install the aircrack-ng/8812au driver.
It needs to be test on the command line before to be ad to the scripts.
That's what I am doing, but it doesn't work now.

```
git clone -b v5.2.20 https://github.com/aircrack-ng/rtl8812au.git
sudo apt-get -y install dkms
sudo apt-get -y install raspberrypi-kernel-headers
cd /home/pi
cd rtl*

sudo ./dkms-install.sh
```
or
```
make
make install
```
