### ISSUE TITLE
Make the image boot on tty1

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#58]
I think it's a very disturbing issue that the image is booting on tty12, because one can't see the state of wifi cards ...
It would be better to show the tty1, like with 1.6RC6.

**Comment by Yes21** [comment]
This can be easily changed in `boot/cmdline.txt`

**Comment by RespawnDespair** [comment]
Which i will change, tty12 was ok for me during testing, but i understand the issue.
I will update the cmdline.txt to use tty1 again.

**Comment by RespawnDespair** [comment]
Changed cmdline

**Comment by rodizio1** [comment]
The console=tty12 cmdline.txt parameter is also present in the original 1.6RC6 image, I used it to hide the boot messages on a different console.

I'm not sure why using this parameter now seems to give different behaviour, something must've changed either with Raspbian or the kernel.
