### ISSUE TITLE
build-image bails on resizefs 

### ISSUE THREAD

**Issue by kwatkins** [RespawnDespair/wifibroadcast-image-builder#6]
Getting this from the latest:
`mount: /root/wifibroadcast-image-builder/data/mnt/boot: overlapping loop device exists for /root/wifibroadcast-image-builder/data/2018-06-27-raspbian-stretch-lite_2018-09-02.img.`

**Comment by RespawnDespair** [comment]
I only get this error when i have another image mounted. Perhaps the script could be modified to handle this situation, but i usually just make sure no other images are mounted. If the script failed mid-run and you are launching again, you could run the lines from ./unmount.sh. This should unmount any leftovers.

**Comment by RespawnDespair** [comment]
@kwatkins is the image building working for you now?

**Comment by kwatkins** [comment]
I gave this a go with latest master, build_images.sh goes through but the resulting img still doesn't look right...
```
root@kali# ls -l data
total 8157496
-rw-r--r--  1 root root 4009754625 Oct 19 16:50 2018-06-27-raspbian-stretch-lite_2018-10-19.img
-rw-r--r--  1 root root 4009754625 Oct 19 16:39 2018-06-27-raspbian-stretch-lite.img
-rw-r--r--  1 root root  366980542 Jun 26 21:10 2018-06-27-raspbian-stretch-lite.zip
drwxr-xr-x 12 root root       4096 Oct 19 16:29 git
drwxr-xr-x  4 root root       4096 Oct 18 13:37 kernel
drwxr-xr-x  2 root root       4096 Oct 19 16:40 mnt
-rw-r--r--  1 root root 2147483649 Oct 19 16:39 temp.img
root@kali# fdisk -l data/2018-06-27-raspbian-stretch-lite_2018-10-19.img 
Disk data/2018-06-27-raspbian-stretch-lite_2018-10-19.img: 3.8 GiB, 4009754624 bytes, 7831552 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x4d3ee428

Device                                                Boot Start     End Sectors  Size Id Type
data/2018-06-27-raspbian-stretch-lite_2018-10-19.img1       8192   96663   88472 43.2M  c W95 FAT32 (LBA)
data/2018-06-27-raspbian-stretch-lite_2018-10-19.img2      98304 7831551 7733248  3.7G 83 Linux
root@kali:~/wifibroadcast/wifibroadcast-image-builder#
```

Then mounting it to look shows it still is the original stretch image, 
root@kali# mount -v -o offset=50331648 -t ext4 ./2018-06-27-raspbian-stretch-lite_2018-10-19.img /mnt/img
root@kali# ls -al /mnt/img/root
total 16
drwx------  2 root root 4096 Jun 26 20:03 .
drwxr-xr-x 22 root root 4096 Jun 26 20:03 ..
-rw-r--r--  1 root root  570 Mar 12  2018 .bashrc
-rw-r--r--  1 root root  148 Mar 12  2018 .profile
```

Likely I'm still missing something?

**Comment by kwatkins** [comment]
Got further along, to patch_rpi_image and moving the boot mount after (seems only one loop0 mount can be active at a time?) 
Now working on resolving the apt-get's, something is going on - still not going through after apt update. 
```
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/p/python2.7/python2.7-dev_2.7.13-2+deb9u2_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

What is exact distro and setup environment we should be running these scripts on?

**Comment by Yes21** [comment]
**@kwatkins** 
I don't understand your problem.
I got today a bootable image at the end of the script.
What is your Linux distribution/version ?

**Comment by kwatkins** [comment]
Ugh, ignore this, I was using the build script from a week ago. Did a git pull origin master and it looks like it's going through. I saw that the stuff I had changed to get the script working was also put in, so, my bad for not getting the latest. 

I'm using a kali image of ubuntu in a virtualbox FM.

**Comment by kwatkins** [comment]
@RespawnDespair you can close this, looks to be fixed in latest build scripts on master. Thanks!
