### ISSUE TITLE
/lib/modules/4.14.71*/build and source symlinks are bad

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#61]
Like in this [issue](https://github.com/RespawnDespair/wifibroadcast-image-builder/issues/43), these links are always pointing to "/home/jelle/git/staged-builder/work/02-Kernel/linux".

**Comment by dposea** [comment]
To make life easier I suggest including the current kernel headers in /usr/src and linking build to them. You may also want to include the patched kernel source in /usr/src and link source to that.

**Comment by Yes21** [comment]
Since the kernel-headers are not installed in the image, those symlinks have nothing to do in it.
So they have to be removed.
Correct symlinks will be automatically created in case of kernel-headers installation.

**Comment by Michael5490** [comment]
Hello
I've tried every possibility b but i dont find out.
How can we delete Symlink ? I use an image and the Kernel headers are not installed in the image. I think this is the sampe problem as you have.

Thx in advance for your help !

KMS: build completed.
Error! echo
Your kernel headers for kernel 4.14.21+ cannot be found at
/lib/modules/4.14.21+/build or /lib/modules/4.14.21+/source.
Error! echo
Your kernel headers for kernel 4.14.21-v7+ cannot be found at
/lib/modules/4.14.21-v7+/build or /lib/modules/4.14.21-v7+/source.
