### ISSUE TITLE
SSH login behavior different between 1.6RC6 and 2.0beta

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#62]
In 1.6RC6 the user to use for SSH login is "root" (see the [wiki](https://github.com/bortek/EZ-WifiBroadcast/wiki/Expert-~-SSH-shell)). If logged with user "pi" the filesystem is "ro".

With 2.0beta, "root" SSH login is refused. So one should log in with "pi" and the filesystem is "rw"

Those differences are very disturbing !

**Comment by Yes21** [comment]
I've perhaps found the difference between 1.6RC6 and 2.0beta.
I will confirm it tomorrow ...

**Comment by Yes21** [comment]
The difference is in this file `/etc/ssh/sshd_config` :

- 1.6RC6 : `#PermitRootLogin yes`
- 2.0beta : `#PermitRootLogin prohibit-password`

But that's not enough. I guess we have to set a ssh password for root.

But I don't know if that's such a good idea to ssh connect directly as root.
I propose to preserve the standard behavior of raspbian (pi/raspberry) ...

What do you think ?

**Comment by RespawnDespair** [comment]
I think the default behaviour is fine. I do not see a need to have a 'root' user. 
And since that is the raspbian standard i'd think they have some good reasons for it...
So i propose to leave it as is.

**Comment by Yes21** [comment]
Ok, I close the issue.
