### ISSUE TITLE
No splashscreen in latest image

### ISSUE THREAD

**Issue by Yes21** [RespawnDespair/wifibroadcast-image-builder#63]
The splashscreen did disappear in latest image/build : https://github.com/bortek/EZ-WifiBroadcast/issues/166#issuecomment-436338684

**Comment by RespawnDespair** [comment]
I'm burning the image now, if i also have the splash i'm closing the issue...

**Comment by RespawnDespair** [comment]
Well i have a splash screen with my latest image as well, so closing this issue.
Need to upgrade the image to 2.0 though...
