### ISSUE TITLE
Cards failing to initialize (on the Pi3B+ only?)

### ISSUE THREAD

**Issue by rodizio1** [RespawnDespair/wifibroadcast-image-builder#68]
Seems like newer kernels have strange USB instabilities during card initialization again :(

Happens randomly with the image-builder image and also with my own test-image based on the 1.6RC6 image. Happens both with kernel 4.14.71 and 4.14.79. Whats strange is, that it also happens with only 2 Ralink cards (Ralink cards always have been less susceptible to those weird USB issues ...)

So far I have only seen in on the Pi3B+, but it seems to be happening randomly, sometimes it works 10 times in a row, then at the next power-cycle it stops working. Sometimes all cards work, sometimes it hangs, sometimes only 2 out of three cards get initialized and I get a picture (but with one card showing no dbm values in the OSD). Could also be just coincidence that I've seen it only on the 3B+, I'll have to do more testing.

[
![img_20181120_143953](https://user-images.githubusercontent.com/21161270/48777305-8a288a00-ecd2-11e8-8b71-738c7e04ecb8.jpg)
](url)

**Comment by RespawnDespair** [comment]
Is this in any way related to the behaviour described by @Yes21 ?

https://github.com/RespawnDespair/wifibroadcast-image-builder/issues/65#issuecomment-440361682

If so, should we try to increase the initial delay between start and trying to access the wifi cards? In order for things to 'settle down'?

**Comment by rodizio1** [comment]
Not sure if it's related to Yes21's findings.

Increasing the delay will most likely not fix it, just mitigate it a little (if at all), this looks like it must be fixed in either the kernel or firmware to me.

I have done some more testing in the meantime, it also happens with Kernel 4.14.32. My next step was to test Kernel 4.9.80 from Raspbian 2018-03-13, but somehow rpi-source doesn't download the correct kernel sources, now I'm stuck with finding out how to get kernel 4.9.80 sources ...

**Comment by rodizio1** [comment]
Still haven't found a way to download a 4.9.80 kernel tar.gz unfortunately.

Have tested with the Pi3B (non-plus) though, it doesn't happen there, only on the Pi3B+.

**Comment by Yes21** [comment]
@pilotnbr1 Many thanks for these testings.
I've no 3b+ nor 3a+, but I'm happy if they are well supported !!

**Comment by RespawnDespair** [comment]
I will make a separate task for moving to the latest raspbian.
This will involve some work with the kernel config again.
I really want to have all other issues resolved before doing that, it will be good practice for the future, that's what i made the builder for 😄 
Closing this as it appears to work.
