### ISSUE TITLE
Settings Capabilities for dumpcap failed

### ISSUE THREAD

**Issue by pilotnbr1** [RespawnDespair/wifibroadcast-image-builder#69]
So running the builder first time. It’s been churning away for 3 hours on my old 2 core toshiba satellite (I think it’s smoking lol). I did not go with the default option regarding non root member privilidges and wireshark (selected yes). Running a fresh install of Ubuntu 18.04LTS 

Now I have encountered two problems one is an error window in terminal showing setting capabilities for dumpcap failed.

The second problem is that I cannot select the <ok> prompt in the above mentioned error window. It’s like I cannot send a “return” to the terminal to select ok (my only option). So now the builder is stuck. I will mess with it some more to see if I can get past this poor mans gui problem.

On a positive note I burned @Yes21 2.0beta image dated 11-05 and had great results so far. Not sure where to post them but

AirPi is running ez-wbc 1.6rc6
Pi zero w
36nha x1

GroundPi 2.0beta
Pi 3b+
722n x1
Official pi 7 inch display

Telemetry, OSD, RC worked with both the pi display only and with android phone tethered running fpv-vr

As reported elsewhere no splash screen.

Nice work! I’ll do more testing with more dongles and also running this 2.0beta image on the airpi

**Comment by pilotnbr1** [comment]
Couldn’t tab to the ok either...

**Comment by Yes21** [comment]
> Now I have encountered two problems one is an error window in terminal showing setting capabilities for dumpcap failed.

Happy to see you trying the builder ;-)

Sorry to be unable to help you, but I've never encountered this issue with the builder ...
I hope you will soon understand what happens.

**Comment by pilotnbr1** [comment]
Second time around was much faster to compile. I went with the default "no" option to the wireshark question and avoided the hangup again. Will test my fresh image tomorrow.

**Comment by Yes21** [comment]
@pilotnbr1 Did you now succeed in building a 2.0beta image ?

**Comment by pilotnbr1** [comment]
Yes! Now on my 10th easily lol

I have one cooking now with quite a few packages removed- we will see :)

**Comment by Yes21** [comment]
@pilotnbr1 Is this issue always pending ?

**Comment by pilotnbr1** [comment]
@Yes21 honestly not sure, but I think so.

This error occurred when selecting “yes” to the wireshark question/prompt.

Now I always select “no” and have not looked into it.

**Comment by Yes21** [comment]
OK, so we need to add this to the readme, and then close the issue.
Danke.

**Comment by Yes21** [comment]
@pilotnbr1 Please could you now close this issue ?

**Comment by pilotnbr1** [comment]
👍
