### ISSUE TITLE
How to build for other SBC's

### ISSUE THREAD

**Issue by chipvk** [RespawnDespair/wifibroadcast-image-builder#91]
Hi,
I want to build EZ-wifibroadcast other than Raspberrypi (like nanopi or tinkerboard). I want to use Debian version only. What are the things I need to take care.

**Comment by Yes21** [comment]
Because this system is based on Raspbian, it can't work on other SBC. Raspbian is designed fro a Raspberry Pi and its CPU and GPU.
On an other SBC, with different CPU and GPU, video, OSD, and perhaps other things (USB ports ?) will not work.
Some people could make in work on a linux pc, but AFAK never on a non Pi SBC.

**Comment by RespawnDespair** [comment]
Well, what @Yes21 says is true to a certain extent.
The kernel modifications etc. can all be made to work on different SBC's.
The Wifibroadcast system itself is heavily dependant on the raspberry pi kernel and tools.
raspivid and the video player used are specific to the Pi.

Supporting different SBC is on my (personal) list of things to achieve. It will be a big effort, not something done in a few days or hours.

**Comment by RespawnDespair** [comment]
As a starting point i wanted to look at:
https://github.com/svpcom/wifibroadcast/issues/19

To see how this could be integrated in the builder.
As stated significant changes need to be made to the Wifibroadcast workings to not rely on raspivid and use gstreamer as a video player.

**Comment by Yes21** [comment]
It seems that Lelik made it work on a nanoPi !
See [here](https://www.rcgroups.com/forums/showpost.php?p=40597723&postcount=6892).

**Comment by chipvk** [comment]
Thank you @Yes21 @RespawnDespair for leads. I will go through all necessary things to perform on other linux/kernel.

**Comment by Yes21** [comment]
@chipvk Good Luck !!

**Comment by Yes21** [comment]
@chipvk As the solution is not here in this github, please could you close this issue ?

**Comment by pilotnbr1** [comment]
One thing to keep in mind is that the Ground side is much easier to use different hardware (pi vs a pc) than the air side. The air side is very dependent on the code tied to the raspberry pi camera hardware and gpu. The ground side you can very easily get just video on a Linux machine. Telemetry is not all that hard to pump into a ground Linux machine as well.

**Comment by chipvk** [comment]
> One thing to keep in mind is that the Ground side is much easier to use different hardware (pi vs a pc) than the air side. The air side is very dependent on the code tied to the raspberry pi camera hardware and gpu. The ground side you can very easily get just video on a Linux machine. Telemetry is not all that hard to pump into a ground Linux machine as well.

Ok
