### ISSUE TITLE
System Tweaks

### ISSUE THREAD

**Issue by pilotnbr1** [RespawnDespair/wifibroadcast-image-builder#95]
Change systemd loglevel to warning.. currently = info

edit also change where the warning is displayed/written
LogTarget=kmsg

Very minor low priority. But if I dont write it down ill forget

**Comment by pilotnbr1** [comment]
Observed a difference in settings 1.6vs2.0 in  /rootfs/etc/sysctl.d/ 98-rpi.conf

1.6 settings below which are almost all missing in 2.0. 
kernel.printk = 3 4 1 3
vm.swappiness=0
vm.min_free_kbytes = 8192

vm.dirty_background_ratio = 1
vm.dirty_ratio = 2
vm.dirty_writeback_centisecs = 25

**Comment by RespawnDespair** [comment]
Should we put this in the overlay?
Might be the quickest way to fix it?

**Comment by pilotnbr1** [comment]
Looks like you got it implemented already, awesome! Sorry I have been sick so somewhat absent. Hoping to put some time into this project over the week.

**Comment by RespawnDespair** [comment]
I didn't change the overlay yet? Are you saying the new build contains this?
That can only be if the kernel compile modifications influence this...
I hope you are feeling better, i've been sick for 2 weeks, lots of germs going around...

**Comment by pilotnbr1** [comment]
My apologies, I thought I had seen in a recent PR that the 98-rpi.conf settings were corrected but not sure what I saw- chalk it up to being sick and confused lol

Yes overlay sounds good.

**Comment by RespawnDespair** [comment]
Added to master branch.
